### ISSUE TITLE
Can not import com.basho.riak.spark.rdd.RiakFunctions

### ISSUE THREAD

**Issue by tuanho27** [basho/spark-riak-connector#198]
Hello,

When I try to using connector, I met the problem. Is there any issue?
Bellow is my env:
**ENV:**
Spark 1.6.2
Riak KV 2.1.4
Spark-riak-connector: 1.5.1

**RUN:**
sbt assembly

**DOC:**
https://github.com/basho/spark-riak-connector/blob/master/docs/using-connector.md

`[error] /home/tuanho/Work/test/src/main/scala/com/firsttest/spark/TestRiak.scala:22: object **RiakFunctions is not a member of package com.basho.riak.spark.rdd**
[error] import com.basho.riak.spark.rdd.RiakFunctions
[error]        ^
[error] /home/tuanho/Work/test/src/main/scala/com/firsttest/spark/TestRiak.scala:46: value saveToRiak is not a member of Unit
[error] possible cause: maybe a semicolon is missing before `value saveToRiak'?
[error] 	.saveToRiak(new Namespace("kv_bucket_a"))
[error] 	 ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 13 s, completed Sep 7, 2016 11:11:13 PM
`

**Comment by srgg** [comment]
@tuanho27  could you please provide a full code snippet to reproduce this issue?

**Comment by tuanho27** [comment]
@srgg this is my code:

`package com.firsttest.spark

import com.basho.riak.client.core.query.Namespace
import com.basho.riak.spark.rdd.RiakFunctions
import org.apache.spark.{SparkContext, SparkConf}
import org.apache.spark.SparkContext._
import com.basho.riak.spark._
/**
 * Really simple demo program which calculates the number of records loaded
 * from the Riak bucket
 */
//
object TestRiak {
  def main(args: Array[String]) {
        val conf = new SparkConf()
           .setMaster("local[*]")
           .setAppName("SparkMyRiak")
           .set("spark.riak.connection.host", "127.0.0.1")
           .set("spark.riak.connections.min", "1") // optional
           .set("spark.riak.connections.max", "50") // optional

        val sc = new SparkContext(conf)
        val data = Array(1, 2, 3, 4, 5)
        val testRDD = sc.parallelize(data)
        println("=======================================================")
        .saveToRiak(new Namespace("kv_bucket_a"))
        val queryRDD = sc.riakBucket[String](new Namespace("kv_bucket_a")).queryAll()
        queryRDD.collect().foreach(println)
        println("Hello, this is first simplest project!@@@@@@@@@@@@@@@")
  }
}
`
**And the build.sbt file**

`name         := "SparkMe Project"
version      := "1.0"
organization := "zentech"

scalaVersion := "2.10.5"

resolvers += Resolver.mavenLocal
//resolvers += "Basho Bintray Repo" at "https://dl.bintray.com/basho/data-platform"
libraryDependencies +=  "com.basho.riak" % "spark-riak-connector" % "1.5.1"
// For avoid deduplicate different file
 assemblyMergeStrategy in assembly := {
  case PathList("org","aopalliance", xs @ _*) => MergeStrategy.last
  case PathList("javax", "inject", xs @ _*) => MergeStrategy.last
  case PathList("javax", "servlet", xs @ _*) => MergeStrategy.last
  case PathList("javax", "activation", xs @ _*) => MergeStrategy.last
  case PathList("org", "apache", xs @ _*) => MergeStrategy.last
  case PathList("com", "google", xs @ _*) => MergeStrategy.last
  case PathList("com", "esotericsoftware", xs @ _*) => MergeStrategy.last
  case PathList("com", "codahale", xs @ _*) => MergeStrategy.last
  case PathList("com", "yammer", xs @ _*) => MergeStrategy.last
  case "about.html" => MergeStrategy.rename
  case "META-INF/ECLIPSEF.RSA" => MergeStrategy.last
  case "META-INF/mailcap" => MergeStrategy.last
  case "META-INF/mimetypes.default" => MergeStrategy.last
  case "plugin.properties" => MergeStrategy.last
  case "log4j.properties" => MergeStrategy.last
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}

`

**Comment by srgg** [comment]
Since RiakFunctions contains various helpers for testing it belongs to the spark-riak-connector-test-utils artifact. You need to add it to your project.

**Comment by srgg** [comment]
BTW yesterday Riak Spark Connector v1.6.0 has been released. [Here is a list of changes](https://github.com/basho/spark-riak-connector/blob/master/CHANGELOG.md)

**Comment by tuanho27** [comment]
@srgg I got you comment & the information.
Actually, I just confuse about the import of RiakFunction at the beginning. It's Ok now.
However, until now, I still can't connect to the Riak by Connector. Some exception occur when I try to submit Fat jar file to Spark. May be I lack of setting something.
But anyway, Thanks for reply.

**Comment by srgg** [comment]
@tuanho27 Could you provide a stack trace?

**Comment by tuanho27** [comment]
@srgg, Below is stack trace. Thanks so much for supporting.

> 16/09/11 18:05:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> ===================run sc.parallelize ======================
> Exception in thread "main" java.util.concurrent.ExecutionException: com.basho.riak.client.core.netty.RiakResponseException: Unknown message code: 70
> 	at com.basho.riak.client.core.FutureOperation.get(FutureOperation.java:314)
> 	at com.basho.riak.client.api.commands.CoreFutureAdapter.get(CoreFutureAdapter.java:52)
> 	at com.basho.riak.client.api.RiakCommand.execute(RiakCommand.java:89)
> 	at com.basho.riak.client.api.RiakClient.execute(RiakClient.java:328)
> 	at com.basho.riak.spark.rdd.connector.CachedSession.execute(SessionCache.scala:233)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.basho.riak.spark.rdd.connector.SessionProxy.invoke(SessionCache.scala:196)
> 	at com.sun.proxy.$Proxy15.execute(Unknown Source)
> 	at com.basho.riak.spark.rdd.partitioner.RiakCoveragePlanBasedPartitioner$$anonfun$partitions$1.apply(RiakCoveragePlanBasedPartitioner.scala:73)
> 	at com.basho.riak.spark.rdd.partitioner.RiakCoveragePlanBasedPartitioner$$anonfun$partitions$1.apply(RiakCoveragePlanBasedPartitioner.scala:64)
> 	at com.basho.riak.spark.rdd.connector.RiakConnector$$anonfun$withSessionDo$1.apply(RiakConnector.scala:58)
> 	at com.basho.riak.spark.rdd.connector.RiakConnector$$anonfun$withSessionDo$1.apply(RiakConnector.scala:58)
> 	at com.basho.riak.spark.rdd.connector.RiakConnector.closeSessionAfterUse(RiakConnector.scala:63)
> 	at com.basho.riak.spark.rdd.connector.RiakConnector.withSessionDo(RiakConnector.scala:58)
> 	at com.basho.riak.spark.rdd.connector.RiakConnector.withSessionDo(RiakConnector.scala:60)
> 	at com.basho.riak.spark.rdd.partitioner.RiakCoveragePlanBasedPartitioner$.partitions(RiakCoveragePlanBasedPartitioner.scala:64)
> 	at com.basho.riak.spark.rdd.RiakRDD.getPartitions(RiakRDD.scala:53)
> 	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
> 	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
> 	at scala.Option.getOrElse(Option.scala:120)
> 	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
> 	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:927)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
> 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
> 	at org.apache.spark.rdd.RDD.collect(RDD.scala:926)
> 	at com.firsttest.spark.TestRiak$.main(TestRiak.scala:45)
> 	at com.firsttest.spark.TestRiak.main(TestRiak.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
> 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
> 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> Caused by: com.basho.riak.client.core.netty.RiakResponseException: Unknown message code: 70
> 	at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:52)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
> 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
> 	at java.lang.Thread.run(Thread.java:745)
> 16/09/11 18:05:57 WARN SessionCache: Session Cleaner was interrunpted
> java.lang.InterruptedException: sleep interrupted
> 	at java.lang.Thread.sleep(Native Method)
> 	at com.basho.riak.spark.rdd.connector.SessionCache$$anon$1.run(SessionCache.scala:166)
> java.lang.ClassNotFoundException: com.firsttest.spark.QueryAll
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at org.apache.spark.util.Utils$.classForName(Utils.scala:175)
> 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:689)
> 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
> 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by srgg** [comment]
@tuanho27

**Comment by srgg** [comment]
@tuanho27 Is there any update on this issue?

**Comment by tuanho27** [comment]
I have not any updated information yet @srgg  
Maybe I will consider to use riak TS later, but It's can make some issue for my system.
> Otherwise, with Riak KV, you could use a range of 2i indexes

For my riak kv config now, I use Bitcask/Multi BE. As the description in this page http://docs.basho.com/riak/kv/2.1.4/using/repair-recovery/errors/
if I do not config to use the LevelDB backend. I can not use 2i 

But, thank you for support, let me close this issue.
